name: CI + Publish
on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno test -A --permit-no-files --parallel --no-check=remote
      - run: deno fmt --check
      - run: deno lint

  publish:
    runs-on: ubuntu-latest
    needs: check
    permissions:
      contents: read
      id-token: write
    if: ((github.event_name == 'push' && github.ref == 'refs/heads/main') || (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')))
    steps:
      - uses: actions/checkout@v4
      - run: npx jsr publish
